### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by mmartinortiz** [Cwiiis/maped#2]
Hi,

I saw your post this morning in Mastodon and decided to give it a try :-). But I'm not sure how to get started, I thought that the easiest would be opening a `map` file from [Ludic break the loop](https://www.amstradcpc.es/doku.php?id=juegos:ludic_break_loop), but that failed. I guess that I used an invalid `map` file.

How could I easily get started with `maped`?

**Comment by Cwiiis** [comment]
The easiest way is to start with an image - you'll need a PNG format file that conforms to the restrictions of the CPC screen mode you pick. If you're working in mode 0, that would mean tile width must be divisible by 2 and no more than 16 colours are used; for mode 1 (which is completely untested :)), that would mean a tile width divisible by 4 and no more than 4 colours used. The PNG must be palettised, but it doesn't matter if there are more palette entries than are used, as long as only the first X number of colours in the palette are used. The app will fail and warn you if the restrictions aren't met.

The .map format is completely proprietary to the app - it's just a zipped JSON file of the main context object. If you rename it to .zip extension, you can have a look.
